rm(list=ls())
library(readxl)
Cuisse_jambe_metrics_CMT1B <- read_excel("//139.124.150.240/data_project/SUPERSEG/CLIN_SEG/For_Aynaz/Excels/Cuisse_jambe_metrics_CMT1B.xlsx", 
                                         col_types = c("text", "text", "text", 
                                                       "text", "numeric", "numeric", "numeric"))
View(Cuisse_jambe_metrics_CMT1B)
cjmP<-Cuisse_jambe_metrics_CMT1B
head(cjmP)
attach(cjmP)
###########################################################################################################################
MT2<-subset(cjmP,Modality=="T2")
MT2
length(MT2$Modality)
MDP<-subset(cjmP,Modality=="DP")
MDP
length(MDP$Modality)
MFF<-subset(cjmP,Modality=="FF")
MFF
length(MFF$Modality)
MMTR<-subset(cjmP,Modality=="MTR")
MMTR
length(MMTR$Modality)
###########################################################################################################################
names(cjmP)
class(ID)
str(cjmP)
ID<-as.factor(ID)
class(ID)
Part<-as.factor(Part)
class(Part)
Labels<-as.factor(Labels)
class(Labels)
Modality<-as.factor(Modality)
class(Modality)
str(cjmP)
levels(ID)
levels(Part)
levels(Labels)
table(Labels)
levels(Modality)
table(Modality)
summary(Labels)
#########################################################################################################################
#test normality
qqplot(mean[Modality=="DP"],Labels[Modality=="DP"])
qqplot(mean[Modality=="FF"],Labels[Modality=="FF"])
qqplot(mean[Modality=="T2"],Labels[Modality=="T2"])
qqplot(mean[Modality=="MTR"],Labels[Modality=="MTR"])
#########################################################################################################################
boxplot(mean[Modality=="DP"]~Labels[Modality=="DP"],las=2)
anova3<-aov(mean[Modality=="DP"]~Labels[Modality=="DP"])
summary(anova3)
TukeyHSD(anova3)
model3<-lm(mean[Modality=="DP"]~Labels[Modality=="DP"])
summary(model3)
pairwise.t.test(mean[Modality=="DP"],Labels[Modality=="DP"])
plot(TukeyHSD(anova3))
plot(anova3,1)
library(car)
leveneTest(mean[Modality=="DP"],Labels[Modality=="DP"])
#res3<-oneway.test(mean[Modality=="DP"],Labels[Modality=="DP"])
#res3
plot(anova3,2)
aov3_residuals<-residuals(object = anova3)
shapiro.test(x=aov3_residuals)
kruskal.test(mean[Modality=="DP"]~Labels[Modality=="DP"])
pairwise.wilcox.test(mean[Modality=="DP"],Labels[Modality=="DP"],p.adjust.method = "BH")
##########################################################################################################################
boxplot(mean[Modality=="FF"]~Labels[Modality=="FF"],las=2)
anova4<-aov(mean[Modality=="FF"]~Labels[Modality=="FF"])
summary(anova4)
TukeyHSD(anova4)
plot(TukeyHSD(anova4))
model4<-lm(mean[Modality=="FF"]~Labels[Modality=="FF"])
summary(model4)
pairwise.t.test(mean[Modality=="FF"],Labels[Modality=="FF"])
library(car)
plot(anova4,1)
leveneTest(mean[Modality=="FF"],Labels[Modality=="FF"])
res4<-oneway.test(mean[Modality=="FF"]~Labels[Modality=="FF"],data = cjmP)
res4
pairwise.t.test(mean[Modality=="FF"],Labels[Modality=="FF"],p.adjust.method = "BH",pool.sd = FALSE)
plot(anova4,2)
aov4_residuals<-residuals(object = anova4)
shapiro.test(x=aov4_residuals)
kruskalwallisFF<-kruskal.test(mean[Modality=="FF"]~Labels[Modality=="FF"])
kruskalwallisFF
pairwise.wilcox.test(mean[Modality=="FF"],Labels[Modality=="FF"],p.adjust.method = "BH")
##########################################################################################################################
boxplot(mean[Modality=="MTR"]~Labels[Modality=="MTR"],las=2)
anova5<-aov(mean[Modality=="MTR"]~Labels[Modality=="MTR"])
summary(anova5)
pairwise.t.test(mean[Modality=="MTR"],Labels[Modality=="MTR"])
TukeyHSD(anova5)
plot(TukeyHSD(anova5))
model5<-lm(mean[Modality=="MTR"]~Labels[Modality=="MTR"])
summary(model5)
library(car)
plot(anova5,1)
leveneTest(mean[Modality=="MTR"],Labels[Modality=="MTR"])
res5<-oneway.test(mean[Modality=="MTR"]~Labels[Modality=="MTR"])
res5
pairwise.t.test(mean[Modality=="MTR"],Labels[Modality=="MTR"],p.adjust.method = "BH",pool.sd = FALSE)
plot(anova5,2)
aov5_residuals<-residuals(object = anova5)
shapiro.test(x=aov5_residuals)
kruskalwallisMTR<-kruskal.test(mean[Modality=="MTR"]~Labels[Modality=="MTR"])
kruskalwallisMTR
pairwise.wilcox.test(mean[Modality=="MTR"],Labels[Modality=="MTR"],p.adjust.method = "BH")
##########################################################################################################################
boxplot(mean[Modality=="T2"]~Labels[Modality=="T2"],las=2)
anova6<-aov(mean[Modality=="T2"]~Labels[Modality=="T2"])
summary(anova6)
pairwise.t.test(mean[Modality=="T2"],Labels[Modality=="T2"])
TukeyHSD(anova6)
plot(TukeyHSD(anova6))
model6<-lm(mean[Modality=="T2"]~Labels[Modality=="T2"])
summary(model6)
library(car)
plot(anova6,1)
leveneTest(mean[Modality=="T2"],Labels[Modality=="T2"])
#res6<-oneway.test(mean[Modality=="T2"]~Labels[Modality=="T2"])
#res6
plot(anova6,2)
aov6_residuals<-residuals(object = anova6)
shapiro.test(x=aov6_residuals)
kruskalwallisT2<-kruskal.test(mean[Modality=="T2"]~Labels[Modality=="T2"])
kruskalwallisT2
pairwise.wilcox.test(mean[Modality=="T2"],Labels[Modality=="T2"],p.adjust.method = "BH")
#########################################################################################################################
plot(mean~Modality)
anova1<-aov(mean~Modality)
summary(anova1)
model1<-lm(mean~Modality-1)
summary(model1)
pairwise.t.test(mean,Modality)
help(levenetest)
TukeyHSD(anova1)
plot(TukeyHSD(anova1))
plot(anova1,1)
library(car)
leveneTest(mean~Modality)
res1<-oneway.test(mean~Modality)
res1
plot(anova1,2)
aov1_residuals<-residuals(object = anova1)
shapiro.test(x=aov1_residuals)
kruskal.test(mean~Modality)
#########################################################################################################################
plot(mean~Labels)
anova2<-aov(mean~Labels)
summary(anova1)
model2<-lm(mean~Labels-1)
summary(model2)
pairwise.t.test(mean,Labels)
TukeyHSD(anova2)
plot(TukeyHSD(anova2))
plot(anova2,1)
install.packages("car")
library(car)
leveneTest(mean~Labels)
#res2<-oneway.test(mean~Labels)
#res2
plot(anova2,2)
aov2_residuals<-residuals(object = anova2)
shapiro.test(x=aov2_residuals)
#kruskal.test(mean~Labels)

