rm(list=ls())
file<-read.csv(file.choose(),header = T,sep =";" )
View(file)
attach(file)
#select DP 
DP=subset(file,Modality=="DP")
FF=subset(file,Modality=="FF")
MTR=subset(file,Modality=="MTR")
T2=subset(file,Modality=="T2")
#****************************************************************
# Analyse de DP
Vastus_intermedius_DP= subset(x = DP, DP$Labels== "Vastus_intermedius" )
Vastus_medialis_DP= subset(x = DP, DP$Labels== "Vastus_medialis" )
Vastus_lateralis_DP= subset(x = DP, DP$Labels== "Vastus_lateralis" )
Redctus_femoris_DP= subset(x = DP, DP$Labels== "Redctus_femoris" )
Adductor_DP= subset(x = DP, DP$Labels== "Adductor" )
Semi_membranous_DP= subset(x = DP, DP$Labels== "Semi_membranous" )
Semi_tendinous_DP= subset(x = DP, DP$Labels== "Semi_tendinous" )
Biceps_femoris_DP= subset(x = DP, DP$Labels== "Biceps_femoris" )
Sartorius_DP= subset(x = DP, DP$Labels== "Sartorius" )
Gracilis_DP= subset(x = DP, DP$Labels== "Gracilis" )
Gastrocnemius_lateralis_DP= subset(x = DP, DP$Labels== "Gastrocnemius_lateralis")
Gastrocnemius_medialis_DP= subset(x = DP, DP$Labels== "Gastrocnemius_medialis")
Anterior_compartment_DP=subset(x= DP,DP$Labels=="Anterior_compartment")
Deep_posterior_compartment_DP=subset(x= DP,DP$Labels=="Deep_posterior_compartment")
Lateral_compartment_DP=subset(x= DP,DP$Labels=="Lateral_compartment")

# DP entre les patients et les témoins pour chaque muscle
wilcox.test(Vastus_intermedius_DP$mean[Vastus_intermedius_DP$Group=="patient"],Vastus_intermedius_DP$mean[Vastus_intermedius_DP$Group=="control"],paired = FALSE)
wilcox.test(Vastus_medialis_DP$mean[Vastus_medialis_DP$Group=="patient"],Vastus_medialis_DP$mean[Vastus_medialis_DP$Group=="control"],paired = FALSE)
wilcox.test(Vastus_lateralis_DP$mean[Vastus_lateralis_DP$Group=="patient"],Vastus_lateralis_DP$mean[Vastus_lateralis_DP$Group=="control"],paired = FALSE)
wilcox.test(Redctus_femoris_DP$mean[Redctus_femoris_DP$Group=="patient"],Redctus_femoris_DP$mean[Redctus_femoris_DP$Group=="control"],paired = FALSE)
wilcox.test(Adductor_DP$mean[Adductor_DP$Group=="patient"],Adductor_DP$mean[Adductor_DP$Group=="control"],paired = FALSE)
wilcox.test(Semi_membranous_DP$mean[Semi_membranous_DP$Group=="patient"],Semi_membranous_DP$mean[Semi_membranous_DP$Group=="control"],paired = FALSE)
wilcox.test(Semi_tendinous_DP$mean[Semi_tendinous_DP$Group=="patient"],Semi_tendinous_DP$mean[Semi_tendinous_DP$Group=="control"],paired = FALSE)
wilcox.test(Biceps_femoris_DP$mean[Biceps_femoris_DP$Group=="patient"],Biceps_femoris_DP$mean[Biceps_femoris_DP$Group=="control"],paired = FALSE)
wilcox.test(Sartorius_DP$mean[Sartorius_DP$Group=="patient"],Sartorius_DP$mean[Sartorius_DP$Group=="control"],paired = FALSE)
wilcox.test(Gracilis_DP$mean[Gracilis_DP$Group=="patient"],Gracilis_DP$mean[Gracilis_DP$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_lateralis_DP$mean[Gastrocnemius_lateralis_DP$Group=="patient"],Gastrocnemius_lateralis_DP$mean[Gastrocnemius_lateralis_DP$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_medialis_DP$mean[Gastrocnemius_medialis_DP$Group=="patient"],Gastrocnemius_medialis_DP$mean[Gastrocnemius_medialis_DP$Group=="control"],paired = FALSE)
wilcox.test(Anterior_compartment_DP$mean[Anterior_compartment_DP$Group=="patient"],Anterior_compartment_DP$mean[Anterior_compartment_DP$Group=="control"],paired = FALSE)
wilcox.test(Deep_posterior_compartment_DP$mean[Deep_posterior_compartment_DP$Group=="patient"],Deep_posterior_compartment_DP$mean[Deep_posterior_compartment_DP$Group=="control"],paired = FALSE)
wilcox.test(Lateral_compartment_DP$mean[Lateral_compartment_DP$Group=="patient"],Lateral_compartment_DP$mean[Lateral_compartment_DP$Group=="control"],paired = FALSE)

#****************************************************************
# Analyse de FF
Vastus_intermedius_FF= subset(x = FF, FF$Labels== "Vastus_intermedius" )
Vastus_medialis_FF= subset(x = FF, FF$Labels== "Vastus_medialis" )
Vastus_lateralis_FF= subset(x = FF, FF$Labels== "Vastus_lateralis" )
Redctus_femoris_FF= subset(x = FF, FF$Labels== "Redctus_femoris" )
Adductor_FF= subset(x = FF, FF$Labels== "Adductor" )
Semi_membranous_FF= subset(x = FF, FF$Labels== "Semi_membranous" )
Semi_tendinous_FF= subset(x = FF, FF$Labels== "Semi_tendinous" )
Biceps_femoris_FF= subset(x = FF, FF$Labels== "Biceps_femoris" )
Sartorius_FF= subset(x = FF, FF$Labels== "Sartorius" )
Gracilis_FF= subset(x = FF, FF$Labels== "Gracilis" )
Gastrocnemius_lateralis_FF= subset(x = FF, FF$Labels== "Gastrocnemius_lateralis")
Gastrocnemius_medialis_FF= subset(x = FF, FF$Labels== "Gastrocnemius_medialis")
Anterior_compartment_FF=subset(x= FF,FF$Labels=="Anterior_compartment")
Deep_posterior_compartment_FF=subset(x= FF,FF$Labels=="Deep_posterior_compartment")
Lateral_compartment_FF=subset(x= FF,FF$Labels=="Lateral_compartment")

# FF entre les patients et les témoins pour chaque muscle
wilcox.test(Vastus_intermedius_FF$mean[Vastus_intermedius_FF$Group=="patient"],Vastus_intermedius_FF$mean[Vastus_intermedius_FF$Group=="control"],paired = FALSE)
wilcox.test(Vastus_medialis_FF$mean[Vastus_medialis_FF$Group=="patient"],Vastus_medialis_FF$mean[Vastus_medialis_FF$Group=="control"],paired = FALSE)
wilcox.test(Vastus_lateralis_FF$mean[Vastus_lateralis_FF$Group=="patient"],Vastus_lateralis_FF$mean[Vastus_lateralis_FF$Group=="control"],paired = FALSE)
wilcox.test(Redctus_femoris_FF$mean[Redctus_femoris_FF$Group=="patient"],Redctus_femoris_FF$mean[Redctus_femoris_FF$Group=="control"],paired = FALSE)
wilcox.test(Adductor_FF$mean[Adductor_FF$Group=="patient"],Adductor_FF$mean[Adductor_FF$Group=="control"],paired = FALSE)
wilcox.test(Semi_membranous_FF$mean[Semi_membranous_FF$Group=="patient"],Semi_membranous_FF$mean[Semi_membranous_FF$Group=="control"],paired = FALSE)
wilcox.test(Semi_tendinous_FF$mean[Semi_tendinous_FF$Group=="patient"],Semi_tendinous_FF$mean[Semi_tendinous_FF$Group=="control"],paired = FALSE)
wilcox.test(Biceps_femoris_FF$mean[Biceps_femoris_FF$Group=="patient"],Biceps_femoris_FF$mean[Biceps_femoris_FF$Group=="control"],paired = FALSE)
wilcox.test(Sartorius_FF$mean[Sartorius_FF$Group=="patient"],Sartorius_FF$mean[Sartorius_FF$Group=="control"],paired = FALSE)
wilcox.test(Gracilis_FF$mean[Gracilis_FF$Group=="patient"],Gracilis_FF$mean[Gracilis_FF$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_lateralis_FF$mean[Gastrocnemius_lateralis_FF$Group=="patient"],Gastrocnemius_lateralis_FF$mean[Gastrocnemius_lateralis_FF$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_medialis_FF$mean[Gastrocnemius_medialis_FF$Group=="patient"],Gastrocnemius_medialis_FF$mean[Gastrocnemius_medialis_FF$Group=="control"],paired = FALSE)
wilcox.test(Anterior_compartment_FF$mean[Anterior_compartment_FF$Group=="patient"],Anterior_compartment_FF$mean[Anterior_compartment_FF$Group=="control"],paired = FALSE)
wilcox.test(Deep_posterior_compartment_FF$mean[Deep_posterior_compartment_FF$Group=="patient"],Deep_posterior_compartment_FF$mean[Deep_posterior_compartment_FF$Group=="control"],paired = FALSE)
wilcox.test(Lateral_compartment_FF$mean[Lateral_compartment_FF$Group=="patient"],Lateral_compartment_FF$mean[Lateral_compartment_FF$Group=="control"],paired = FALSE)

#****************************************************************
# Analyse de MTR
Vastus_intermedius_MTR= subset(x = MTR, MTR$Labels== "Vastus_intermedius" )
Vastus_medialis_MTR= subset(x = MTR, MTR$Labels== "Vastus_medialis" )
Vastus_lateralis_MTR= subset(x = MTR, MTR$Labels== "Vastus_lateralis" )
Redctus_femoris_MTR= subset(x = MTR, MTR$Labels== "Redctus_femoris" )
Adductor_MTR= subset(x = MTR, MTR$Labels== "Adductor" )
Semi_membranous_MTR= subset(x = MTR, MTR$Labels== "Semi_membranous" )
Semi_tendinous_MTR= subset(x = MTR, MTR$Labels== "Semi_tendinous" )
Biceps_femoris_MTR= subset(x = MTR, MTR$Labels== "Biceps_femoris" )
Sartorius_MTR= subset(x = MTR, MTR$Labels== "Sartorius" )
Gracilis_MTR= subset(x = MTR, MTR$Labels== "Gracilis" )
Gastrocnemius_lateralis_MTR= subset(x = MTR, MTR$Labels== "Gastrocnemius_lateralis")
Gastrocnemius_medialis_MTR= subset(x = MTR, MTR$Labels== "Gastrocnemius_medialis")
Anterior_compartment_MTR=subset(x= MTR,MTR$Labels=="Anterior_compartment")
Deep_posterior_compartment_MTR=subset(x= MTR,MTR$Labels=="Deep_posterior_compartment")
Lateral_compartment_MTR=subset(x= MTR,MTR$Labels=="Lateral_compartment")

# MTR entre les patients et les témoins pour chaque muscle
wilcox.test(Vastus_intermedius_MTR$mean[Vastus_intermedius_MTR$Group=="patient"],Vastus_intermedius_MTR$mean[Vastus_intermedius_MTR$Group=="control"],paired = FALSE)
wilcox.test(Vastus_medialis_MTR$mean[Vastus_medialis_MTR$Group=="patient"],Vastus_medialis_MTR$mean[Vastus_medialis_MTR$Group=="control"],paired = FALSE)
wilcox.test(Vastus_lateralis_MTR$mean[Vastus_lateralis_MTR$Group=="patient"],Vastus_lateralis_MTR$mean[Vastus_lateralis_MTR$Group=="control"],paired = FALSE)
wilcox.test(Redctus_femoris_MTR$mean[Redctus_femoris_MTR$Group=="patient"],Redctus_femoris_MTR$mean[Redctus_femoris_MTR$Group=="control"],paired = FALSE)
wilcox.test(Adductor_MTR$mean[Adductor_MTR$Group=="patient"],Adductor_MTR$mean[Adductor_MTR$Group=="control"],paired = FALSE)
wilcox.test(Semi_membranous_MTR$mean[Semi_membranous_MTR$Group=="patient"],Semi_membranous_MTR$mean[Semi_membranous_MTR$Group=="control"],paired = FALSE)
wilcox.test(Semi_tendinous_MTR$mean[Semi_tendinous_MTR$Group=="patient"],Semi_tendinous_MTR$mean[Semi_tendinous_MTR$Group=="control"],paired = FALSE)
wilcox.test(Biceps_femoris_MTR$mean[Biceps_femoris_MTR$Group=="patient"],Biceps_femoris_MTR$mean[Biceps_femoris_MTR$Group=="control"],paired = FALSE)
wilcox.test(Sartorius_MTR$mean[Sartorius_MTR$Group=="patient"],Sartorius_MTR$mean[Sartorius_MTR$Group=="control"],paired = FALSE)
wilcox.test(Gracilis_MTR$mean[Gracilis_MTR$Group=="patient"],Gracilis_MTR$mean[Gracilis_MTR$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_lateralis_MTR$mean[Gastrocnemius_lateralis_MTR$Group=="patient"],Gastrocnemius_lateralis_MTR$mean[Gastrocnemius_lateralis_MTR$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_medialis_MTR$mean[Gastrocnemius_medialis_MTR$Group=="patient"],Gastrocnemius_medialis_MTR$mean[Gastrocnemius_medialis_MTR$Group=="control"],paired = FALSE)
wilcox.test(Anterior_compartment_MTR$mean[Anterior_compartment_MTR$Group=="patient"],Anterior_compartment_MTR$mean[Anterior_compartment_MTR$Group=="control"],paired = FALSE)
wilcox.test(Deep_posterior_compartment_MTR$mean[Deep_posterior_compartment_MTR$Group=="patient"],Deep_posterior_compartment_MTR$mean[Deep_posterior_compartment_MTR$Group=="control"],paired = FALSE)
wilcox.test(Lateral_compartment_MTR$mean[Lateral_compartment_MTR$Group=="patient"],Lateral_compartment_MTR$mean[Lateral_compartment_MTR$Group=="control"],paired = FALSE)

#****************************************************************
# Analyse de T2
Vastus_intermedius_T2= subset(x = T2, T2$Labels== "Vastus_intermedius" )
Vastus_medialis_T2= subset(x = T2, T2$Labels== "Vastus_medialis" )
Vastus_lateralis_T2= subset(x = T2, T2$Labels== "Vastus_lateralis" )
Redctus_femoris_T2= subset(x = T2, T2$Labels== "Redctus_femoris" )
Adductor_T2= subset(x = T2, T2$Labels== "Adductor" )
Semi_membranous_T2= subset(x = T2, T2$Labels== "Semi_membranous" )
Semi_tendinous_T2= subset(x = T2, T2$Labels== "Semi_tendinous" )
Biceps_femoris_T2= subset(x = T2, T2$Labels== "Biceps_femoris" )
Sartorius_T2= subset(x = T2, T2$Labels== "Sartorius" )
Gracilis_T2= subset(x = T2, T2$Labels== "Gracilis" )
Gastrocnemius_lateralis_T2= subset(x = T2, T2$Labels== "Gastrocnemius_lateralis")
Gastrocnemius_medialis_T2= subset(x = T2, T2$Labels== "Gastrocnemius_medialis")
Anterior_compartment_T2=subset(x= T2,T2$Labels=="Anterior_compartment")
Deep_posterior_compartment_T2=subset(x= T2,T2$Labels=="Deep_posterior_compartment")
Lateral_compartment_T2=subset(x= T2,T2$Labels=="Lateral_compartment")

# T2 entre les patients et les témoins pour chaque muscle
wilcox.test(Vastus_intermedius_T2$mean[Vastus_intermedius_T2$Group=="patient"],Vastus_intermedius_T2$mean[Vastus_intermedius_T2$Group=="control"],paired = FALSE)
wilcox.test(Vastus_medialis_T2$mean[Vastus_medialis_T2$Group=="patient"],Vastus_medialis_T2$mean[Vastus_medialis_T2$Group=="control"],paired = FALSE)
wilcox.test(Vastus_lateralis_T2$mean[Vastus_lateralis_T2$Group=="patient"],Vastus_lateralis_T2$mean[Vastus_lateralis_T2$Group=="control"],paired = FALSE)
wilcox.test(Redctus_femoris_T2$mean[Redctus_femoris_T2$Group=="patient"],Redctus_femoris_T2$mean[Redctus_femoris_T2$Group=="control"],paired = FALSE)
wilcox.test(Adductor_T2$mean[Adductor_T2$Group=="patient"],Adductor_T2$mean[Adductor_T2$Group=="control"],paired = FALSE)
wilcox.test(Semi_membranous_T2$mean[Semi_membranous_T2$Group=="patient"],Semi_membranous_T2$mean[Semi_membranous_T2$Group=="control"],paired = FALSE)
wilcox.test(Semi_tendinous_T2$mean[Semi_tendinous_T2$Group=="patient"],Semi_tendinous_T2$mean[Semi_tendinous_T2$Group=="control"],paired = FALSE)
wilcox.test(Biceps_femoris_T2$mean[Biceps_femoris_T2$Group=="patient"],Biceps_femoris_T2$mean[Biceps_femoris_T2$Group=="control"],paired = FALSE)
wilcox.test(Sartorius_T2$mean[Sartorius_T2$Group=="patient"],Sartorius_T2$mean[Sartorius_T2$Group=="control"],paired = FALSE)
wilcox.test(Gracilis_T2$mean[Gracilis_T2$Group=="patient"],Gracilis_T2$mean[Gracilis_T2$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_lateralis_T2$mean[Gastrocnemius_lateralis_T2$Group=="patient"],Gastrocnemius_lateralis_T2$mean[Gastrocnemius_lateralis_T2$Group=="control"],paired = FALSE)
wilcox.test(Gastrocnemius_medialis_T2$mean[Gastrocnemius_medialis_T2$Group=="patient"],Gastrocnemius_medialis_T2$mean[Gastrocnemius_medialis_T2$Group=="control"],paired = FALSE)
wilcox.test(Anterior_compartment_T2$mean[Anterior_compartment_T2$Group=="patient"],Anterior_compartment_T2$mean[Anterior_compartment_T2$Group=="control"],paired = FALSE)
wilcox.test(Deep_posterior_compartment_T2$mean[Deep_posterior_compartment_T2$Group=="patient"],Deep_posterior_compartment_T2$mean[Deep_posterior_compartment_T2$Group=="control"],paired = FALSE)
wilcox.test(Lateral_compartment_T2$mean[Lateral_compartment_T2$Group=="patient"],Lateral_compartment_T2$mean[Lateral_compartment_T2$Group=="control"],paired = FALSE)








