rm(list=ls())
Controls<-read.csv(file.choose(),header = T,sep =";" )
ls()
Controls<-data.frame(Controls)
attach(Controls)
ID<-as.factor(ID)
class(ID)
Part<-as.factor(Part)
class(Part)
Labels<-as.factor(Labels)
class(Labels)
Modality<-as.factor(Modality)
class(Modality)
mean<-as.numeric(mean)
class(mean)
std<-as.numeric(std)
class(std)
volume<-as.numeric(volume)
class(volume)
levels(ID)
levels(Part)
levels(Labels)
levels(Modality)
summary(Controls)
index=Controls$Part=="cuisse"
Controls.cuisse=Controls[index,]
summary(Controls.cuisse)
index1=Controls$Part=="jambe"
Controls.jambe=Controls[index1,]
summary(Controls.jambe)

library("ggpubr")
ggboxplot(Controls.cuisse, x = "Labels", y = "mean", color = "Modality")
ggboxplot(Controls.jambe, x = "Labels", y = "mean", color = "Modality")

boxplot(mean[Modality=="DP"]~Labels[Modality=="DP"],las=2,data = Controls.cuisse)
qqnorm(Controls.cuisse$mean[Modality=="DP"])
qqline(Controls.cuisse$mean[Modality=="DP"])
shapiro.test(Controls.cuisse$mean[Modality=="DP"])
hist(Controls.cuisse$mean[Modality=="DP"],freq = FALSE)
wilcox.test(mean[Modality=="DP"]~Labels[Modality=="DP"], data = Controls.cuisse)

boxplot(mean[Modality=="FF"]~Labels[Modality=="FF"],las=2,data = Controls.cuisse)
qqnorm(Controls.cuisse$mean[Modality=="FF"])
qqline(Controls.cuisse$mean[Modality=="FF"])
shapiro.test(Controls.cuisse$mean[Modality=="FF"])
hist(Controls.cuisse$mean[Modality=="FF"],freq = FALSE)
wilcox.test(mean[Modality=="FF"]~Labels[Modality=="FF"], data = Controls.cuisse)

boxplot(mean[Modality=="MTR"]~Labels[Modality=="MTR"],las=2,data = Controls.cuisse)
qqnorm(Controls.cuisse$mean[Modality=="MTR"])
qqline(Controls.cuisse$mean[Modality=="MTR"])
shapiro.test(Controls.cuisse$mean[Modality=="MTR"])
hist(Controls.cuisse$mean[Modality=="MTR"],freq = FALSE)
wilcox.test(mean[Modality=="MTR"]~Labels[Modality=="MTR"], data = Controls.cuisse)

boxplot(mean[Modality=="T2"]~Labels[Modality=="T2"],las=2,data = Controls.cuisse)
qqnorm(Controls.cuisse$mean[Modality=="T2"])
qqline(Controls.cuisse$mean[Modality=="T2"])
shapiro.test(Controls.cuisse$mean[Modality=="T2"])
hist(Controls.cuisse$mean[Modality=="T2"],freq = FALSE)
wilcox.test(mean[Modality=="T2"]~Labels[Modality=="T2"], data = Controls.cuisse)

boxplot(mean[Modality=="DP"]~Labels[Modality=="DP"],las=2,data = Controls.jambe)
qqnorm(Controls.jambe$mean[Modality=="DP"])
qqline(Controls.jambe$mean[Modality=="DP"])
shapiro.test(Controls.jambe$mean[Modality=="DP"])
hist(Controls.jambe$mean[Modality=="DP"],freq = FALSE)
wilcox.test(mean[Modality=="DP"]~Labels[Modality=="DP"], data = Controls.jambe)

boxplot(mean[Modality=="FF"]~Labels[Modality=="FF"],las=2,data = Controls.jambe)
qqnorm(Controls.jambe$mean[Modality=="FF"])
qqline(Controls.jambe$mean[Modality=="FF"])
shapiro.test(Controls.jambe$mean[Modality=="FF"])
hist(Controls.jambe$mean[Modality=="FF"],freq = FALSE)
wilcox.test(mean[Modality=="FF"]~Labels[Modality=="FF"], data = Controls.jambe)

boxplot(mean[Modality=="MTR"]~Labels[Modality=="MTR"],las=2,data = Controls.jambe)
qqnorm(Controls.jambe$mean[Modality=="MTR"])
qqline(Controls.jambe$mean[Modality=="MTR"])
shapiro.test(Controls.jambe$mean[Modality=="MTR"])
hist(Controls.jambe$mean[Modality=="MTR"],freq = FALSE)
wilcox.test(mean[Modality=="MTR"]~Labels[Modality=="MTR"], data = Controls.jambe)

boxplot(mean[Modality=="T2"]~Labels[Modality=="T2"],las=2,data = Controls.jambe)
qqnorm(Controls.jambe$mean[Modality=="T2"])
qqline(Controls.jambe$mean[Modality=="T2"])
shapiro.test(Controls.jambe$mean[Modality=="T2"])
hist(Controls.jambe$mean[Modality=="T2"],freq = FALSE)
wilcox.test(mean[Modality=="T2"]~Labels[Modality=="T2"], data = Controls.jambe)

